version: '3.8'

services:
  nodered:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodered
    environment:
      - ROS_MASTER_URI=http://roscore:11311
      - FLOWS=/data/flows.json
    networks:
      - rosserial-tcp-server-docker_default
    ports:
      - "1880:1880"
    # volumes:
      # - nodered_data:/data

networks:
  rosserial-tcp-server-docker_default:
    external: true

# volumes:
#   nodered_data:
